name: first workflow
on:
  push:
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: print working-directory
        run: pwd
      - name: echo command
        run: echo welcome to first workflow
